### PR TITLE
Mspec 0.9.x update

### PR DESCRIPTION
**Pull request by drauch**
I've updated to a new Machine.Specifications version (0.9.3), this is necessary as the newest version does not contain a .ShouldBeOfType<T>() assertion method anymore, and is therefore no longer binary-compatible with your Machine.Specifications.Mvc build.

Please merge the PR and update the corresponding NuGet package so that we can finally update Machine.Specifications at our place.

Thanks in advance & best regards,
D.R.

### CODE REVIEW

**Comment by drauch** [comment]
Note: yes, `ShouldBeOfType()` is semantically equivalent to the new `ShouldBeAssignableTo()` (which is exactly why the name has changed).

**Comment by ulrichb** [comment]
I would also like to update the MSpec library, and therefore would need an updated `Machine.Specifications.Mvc5` package with this fix.

**Comment by drauch** [comment]
Nice, I already assumed the project is dead. Could you please update the corresponding NuGet package as well, I'd love that!

For future issues: is there any way to contact you directly?

**Comment by joefeser** [comment]
https://www.nuget.org/packages/Machine.Specifications.Mvc5/1.9.3

**Comment by joefeser** [comment]
My email should be part of my profile.

**Pull request merged**
