### PR TITLE
Update to Mvc5

### PR DESCRIPTION
**Pull request by flytzen**
Update to support MVC5. It is mainly just a matter of recompiling against the new dlls.

Also changed to use Nuget to pull the dependencies on system.web.mvc as that seems to be the way things are going.

Not 100% sure that I got the version scheme correct.

### CODE REVIEW

**Comment by joefeser** [comment]
I could not merge into master (not your fault). I created a new branch so that I could create a new nuget package. The v5 nuget is https://www.nuget.org/packages/Machine.Specifications.Mvc5/ 

If I made a mistake, please make a patch against the mvc5 branch.

**Comment by flytzen** [comment]
Hi Joe,

Thanks for that! I assume it was to do with the MSpec version? Anyway, I’ll give it a test. 

Did you still need me to update MSpec?

Thanks,

Frans

**Comment by joefeser** [comment]
If you have time, either branch mvc5 or download the nuget package. I was
able to upgrade to 0.6.2 with some work.

Thank you for the pull request.

**Comment by flytzen** [comment]
Leave it with me.

**Pull request closed without merging**
